### ISSUE TITLE
New RFC: Setting environment variables with Cargo's configuration for targets

### ISSUE THREAD

**Issue by zitsen** [rust-lang/rfcs#1629]
- Feature Name: cargo_target_env_config
- Start Date: 2016-05-24
- RFC PR: (leave this empty)
- Rust Issue: (leave this empty)
# Summary

Support setting global and target-specific environment variables in Cargo's configuration.
# Motivation

**I'm not sure to start from this project or rust-lang/cargo, glad to move.**

Suppose while cross-compiling `openssl`, rustacean now would run like this:

```
OPENSSL_INCLUDE_DIR=XXXXX \
    OPENSSL_LIB_DIR=XXXXXXXX \
    cargo build --target some-target ....
```

If target environment config is supported, just config like this:

``` toml
[target.x86_64-unkown-linux-musl.environments]
OPENSSL_INCLUDE_DIR = "/usr/local/musl/include/"
OPENSSL_LIB_DIR = "/usr/local/musl/lib/"
OPENSSL_STATIC = "1"
```

And then simlely run `cargo build --target x86_64-unkown-linux-musl` as normal.

It's easy to set different variables for different targets.
# Detailed design

Both global and target-specific environments should be supported.
### Global environments

``` toml
[environments]
ENV_A = "Global env A"
```
### Target-specific environments

``` toml
[target.x86_64-unkown-linux-musl.environments]
ENV_A = "MUSL specific ENV A"
```
# Drawbacks

Why should we _not_ do this?
# Alternatives

What other designs have been considered? What is the impact of not doing this?
# Unresolved questions

What parts of the design are still TBD?
