### ISSUE TITLE
Remote cargo client/server API/Plugin Architecture for custom package sources

### ISSUE THREAD

**Issue by jpedrick** [rust-lang/rfcs#3561]
A frequent requirement for larger organizations is that some common code may not be "open source" within the organization, with access being limited to a small team. However, Rust crates need to be recompiled to match the exact version of Rust. This ticket is an attempt to resolve that contradiction by allowing an organization to deploy a `cargo server` that provides all of the build targets/artifacts that would normally be build on the users system.

This could have additional benefits, cost and environmental impact, for organizations by allowing sharing of compute resources and build artifacts(if many users are building the same crate, avoid rebuilding by hashing the inputs and returning the already built artifacts). Additionally, this would allow for distributed builds.

```toml
[dependencies]
package_a = { remote = "192.168.1.123:54321", version = "1.1" }
package_b::subpackage = { remote = "192.168.1.124:54321" }

# or build with a federation of remotes, which would query each server and use the one with the shortest build queue
package_a = { remote = [ "192.168.1.123:54321", "192.168.1.124:54321" ] }
package_b::subpackage = { remote = [ "192.168.1.123:54321", "192.168.1.124:54321" ] }
```

Fully implementing this is cargo could be a fools errand, but a remote source plugin/API would allow organizations to build their own remote client/server layers(where servers could download/manage the correct version of Rust, etc.)

```toml
[dependencies]
package_a = { remote = "192.168.1.123:54321", remote_plugin = "cargo-ssh", version = "1.1" } # This would SSH into a remote server to build the package and return the artifacts
package_b::subpackage = { remote = "192.168.1.124:54321", remote_plugin = "cargo-ship" } # I think "cargo-ship" would be a clever name for the first remote cargo repository ;)
```
